version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_03:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - MYSQL_ROOT_PASSWORD=password

  php:
    image: phpapache
    ports:
      - 81:80

volumes:
  mysql_03:
    external: true